<?php
echo 'PHP Libsodium Argon2 parameter' . PHP_EOL . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_SALTBYTES:            ' . SODIUM_CRYPTO_PWHASH_SALTBYTES . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE: ' . SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE: ' . SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE:    ' . SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE:    ' . SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_OPSLIMIT_SENSITIVE:   ' . SODIUM_CRYPTO_PWHASH_OPSLIMIT_SENSITIVE . PHP_EOL;
echo 'SODIUM_CRYPTO_PWHASH_MEMLIMIT_SENSITIVE:   ' . SODIUM_CRYPTO_PWHASH_MEMLIMIT_SENSITIVE . PHP_EOL;

echo 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID      :   ' . SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 . PHP_EOL;
echo 'SODIUM_CRYPTO_SECRETBOX_KEYBYTES:          ' . SODIUM_CRYPTO_SECRETBOX_KEYBYTES . PHP_EOL;
/*
PHP Libsodium Argon2 parameter

SODIUM_CRYPTO_PWHASH_SALTBYTES:            16
SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE: 2
SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE: 67108864
SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE:    3
SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE:    268435456
SODIUM_CRYPTO_PWHASH_OPSLIMIT_SENSITIVE:   4
SODIUM_CRYPTO_PWHASH_MEMLIMIT_SENSITIVE:   1073741824
SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID      :   2
SODIUM_CRYPTO_SECRETBOX_KEYBYTES:          32
*/
?>
